meta_product_name: "Bruyère"
meta_title: "La main verte avec Bruyère"
meta_description: "Entretenez vos plantes et apprenez de leurs caprices, Bruyère vous aide à mieux les aimer !"
meta_image: "cover.png"
twitter_account: "@bruyere"
